### PR TITLE
ScriptEngineManager

### PR DESCRIPTION
**Pull request by Tanguygab**
Hey 🖐
I was looking through the code to try to understand why in the world wouldn't the expansion detect Graal.js nor the JSEngine plugin and I've noticed that the expansion just created a new instance of the ScriptEngineManager while it could (should?) use the Bukkit ServicesManager.
I've realized that it might have been the cause JSEngine states it on its Spigot page
image

So I tried to use that, and it turns out it detected Graal.js correctly!
image
Idk with JSEngine since I was lazy to try x) but I guess it should work as well.
Anyways, hopefully this helps =)

### CODE REVIEW

**Comment by Tanguygab** [comment]
I've just tested and it doesn't seem to detect JSEngnie anyway, I'll try to search a bit more

**Comment by Tanguygab** [comment]
welp, it does work in the end, you just have to use `JavaScript` as engine, case sensitive, idk why `js` didn't work while it was listed

**Comment by darbyjack** [comment]
Does this work on Java 16?

**Comment by Tanguygab** [comment]
that's what I tried on

**Comment by darbyjack** [comment]
Alrighty well thank you for your time and consideration but internally we have already discussed how we plan to move forward with this expansion and our changes will be implemented in the next week or so.

**Comment by Tanguygab** [comment]
Alright! I'll just close the pr then, looking forward to that update 👀

**Pull request closed without merging**
