### PR TITLE
Call ScriptEngineManager with null in constructor 

### PR DESCRIPTION
**Pull request by kangarko**
Fixes https://github.com/PlaceholderAPI/PlaceholderAPI/issues/426

### CODE REVIEW

**Comment by thienbao860** [comment]
What purpose does that serve?

**Comment by kangarko** [comment]
Have you read the "Fixes ..." above? It aims to solve a failure in getting the script engine on newer Minecraft versions.

**Comment by thienbao860** [comment]
Oh i see now.

**Comment by kangarko** [comment]
Thank you!

**Pull request merged**
