### PR TITLE
Shaded Nashorn + QuickJS suppourt

### PR DESCRIPTION
**Pull request by Vshnv**
[+] Shaded in Nashorn + QuickJS
[+] Added QJS as alternative engine for users who want to use ES2020 specs
[+] Cleaned up old code

### CODE REVIEW

**Comment by exzolink** [comment]
Is Cyrillic supported?

**Comment by Vshnv** [comment]
The issue with the unicode handling was reported earlier. A fix to that will be pushed along with the next build.

**Comment by exzolink** [comment]
Got it, thanks

**Comment by CroaBeast** [comment]
I recently upgrade my server to 1.17 and Java 16.
In PAPI Discord they told me to use the last version in the `#1_17` channel, but even so, my scripts are not working.

Error: [Click here](https://paste.helpch.at/uboqonomev.shell)
The script: [Click here](https://paste.helpch.at/eyixoyalar.cs)

**Comment by Vshnv** [comment]
@exzolink Fixed issue with UTF-8 characters in latest build available in #1_17

**Comment by exzolink** [comment]
Thanks

**Review by darbyjack — APPROVED** [review]

**Pull request merged**
